version: '3.8'

services:
  back:
    image: hbimen/back:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  front:
    image: hbimen/front:1.0.0
    ports:
      - "4200:4200"