version: '3'

services:

  spring_app_backend:
    image: image_backend:latest # Update with your Docker image name and tag
    ports:
      - "8082:8082" # Map container port 8080 to host port 8080
    depends_on:
      - mysql # Ensure MySQL container starts before the Spring Boot ap

  spring_app_frontend:
    image: image_frontend:latest # Update with your Docker image name and tag
    ports:
      - "4200:4200"

  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306" # Map container port 3306 to host port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root # Set the MySQL root password
      MYSQL_DATABASE: devops # Create a database named 'mydatabase'
